/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realestate;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }
    
    public String title;
    public String description;
    public String status;
    public String price;
    public String bedrooms;
    public String baths;
    public String area;
    public String block;
    public String subdivisionName;
    public String photo;
    public String media;
    public String province;
    public String city;
    public String barangay;
    public String street;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertiesPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        listPropertyPanel = new javax.swing.JPanel();
        listPropertyNameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPropertyPanelHoder = new javax.swing.JPanel();
        locationTab1 = new realestate.LocationTab();
        genInformationTab2 = new realestate.GenInformationTab();
        keyInformationTab2 = new realestate.KeyInformationTab();
        photosAndMediaTab2 = new realestate.PhotosAndMediaTab();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        managementPropertyTab = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 820));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar.setBackground(new java.awt.Color(217, 217, 217));

        jButton2.setBackground(new java.awt.Color(217, 217, 217));
        jButton2.setFont(new java.awt.Font("Lato", 1, 23)); // NOI18N
        jButton2.setText("Manage Properties");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(217, 217, 217));
        jButton1.setFont(new java.awt.Font("Lato", 1, 23)); // NOI18N
        jButton1.setText("Dashboard");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(217, 217, 217));
        jButton6.setFont(new java.awt.Font("Lato", 1, 23)); // NOI18N
        jButton6.setText("Log Out");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(217, 217, 217));
        jButton7.setFont(new java.awt.Font("Lato", 1, 23)); // NOI18N
        jButton7.setText("Appointments");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1)
                .addGap(139, 139, 139)
                .addComponent(jButton2)
                .addGap(155, 155, 155)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(169, 169, 169))
        );

        jButton2.getAccessibleContext().setAccessibleName("");
        jButton1.getAccessibleContext().setAccessibleName("");

        mainPanel.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 910));
        sideBar.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setRequestFocusEnabled(false);

        dashboardPanel.setBackground(new java.awt.Color(242, 235, 217));

        jPanel2.setBackground(new java.awt.Color(242, 235, 217));

        jComboBox1.setBackground(new java.awt.Color(217, 217, 217));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sell", "Rent" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(217, 217, 217));
        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Condominium", "Commercial", "Apartment", "House", "Land" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Enter Location");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1)
                    .addComponent(jComboBox2)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(242, 235, 217));
        jScrollPane1.setForeground(new java.awt.Color(242, 235, 217));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        propertiesPanel.setBackground(new java.awt.Color(242, 235, 217));
        propertiesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        propertiesPanel.setPreferredSize(new java.awt.Dimension(845, 4969));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 30);
        flowLayout1.setAlignOnBaseline(true);
        propertiesPanel.setLayout(flowLayout1);
        jScrollPane1.setViewportView(propertiesPanel);

        jPanel1.setBackground(new java.awt.Color(255, 252, 182));

        jButton4.setBackground(new java.awt.Color(243, 255, 99));
        jButton4.setFont(new java.awt.Font("Lato", 1, 23)); // NOI18N
        jButton4.setText("List your Property ");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", dashboardPanel);

        listPropertyPanel.setBackground(new java.awt.Color(255, 255, 255));

        listPropertyNameLabel.setFont(new java.awt.Font("Montserrat Alternates Medium", 1, 24)); // NOI18N
        listPropertyNameLabel.setText("List Property Tab");

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listPropertyPanelHoder.setBackground(new java.awt.Color(239, 241, 245));
        listPropertyPanelHoder.setPreferredSize(new java.awt.Dimension(845, 3800));
        listPropertyPanelHoder.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                listPropertyPanelHoderMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout listPropertyPanelHoderLayout = new javax.swing.GroupLayout(listPropertyPanelHoder);
        listPropertyPanelHoder.setLayout(listPropertyPanelHoderLayout);
        listPropertyPanelHoderLayout.setHorizontalGroup(
            listPropertyPanelHoderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPropertyPanelHoderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listPropertyPanelHoderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photosAndMediaTab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genInformationTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyInformationTab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationTab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listPropertyPanelHoderLayout.setVerticalGroup(
            listPropertyPanelHoderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPropertyPanelHoderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genInformationTab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keyInformationTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(photosAndMediaTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 1384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locationTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(listPropertyPanelHoder);

        jButton3.setText("Publish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listPropertyPanelLayout = new javax.swing.GroupLayout(listPropertyPanel);
        listPropertyPanel.setLayout(listPropertyPanelLayout);
        listPropertyPanelLayout.setHorizontalGroup(
            listPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPropertyPanelLayout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addGroup(listPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPropertyPanelLayout.createSequentialGroup()
                        .addComponent(listPropertyNameLabel)
                        .addGap(379, 379, 379))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPropertyPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(listPropertyPanelLayout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listPropertyPanelLayout.setVerticalGroup(
            listPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPropertyPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(listPropertyNameLabel)
                .addGap(18, 18, 18)
                .addGroup(listPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", listPropertyPanel);

        jLabel8.setText("Manage properties");

        javax.swing.GroupLayout managementPropertyTabLayout = new javax.swing.GroupLayout(managementPropertyTab);
        managementPropertyTab.setLayout(managementPropertyTabLayout);
        managementPropertyTabLayout.setHorizontalGroup(
            managementPropertyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPropertyTabLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel8)
                .addContainerGap(1075, Short.MAX_VALUE))
        );
        managementPropertyTabLayout.setVerticalGroup(
            managementPropertyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managementPropertyTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(802, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", managementPropertyTab);

        mainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -45, 1320, 910));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        mainPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void displayAllProperties() {
        
        try {
            
            File file = new File("properties.txt");
            
            BufferedReader reader = new BufferedReader(new FileReader(file));
            
            String line;
            while((line = reader.readLine()) != null) {
                String[] propertyDetails = line.split(",");
                
                JPanel newPropertyPanel = new JPanel();
                
                JLabel photo = new javax.swing.JLabel();
                JLabel title = new javax.swing.JLabel();
                JLabel bed = new javax.swing.JLabel();
                JLabel bath = new javax.swing.JLabel();
                JLabel area = new javax.swing.JLabel();
                JLabel price = new javax.swing.JLabel();
                JPanel panelHolderLocation = new javax.swing.JPanel();
                JLabel street = new javax.swing.JLabel();
                JLabel city = new javax.swing.JLabel();
                JLabel barangay = new javax.swing.JLabel();
                JLabel province = new javax.swing.JLabel();

                newPropertyPanel.setBackground(new java.awt.Color(253, 245, 230));
                newPropertyPanel.setPreferredSize(new java.awt.Dimension(270, 300));

                photo.setText("Image");

                title.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
                title.setText("jLabel2");

                bed.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
                bed.setText("jLabel2");

                bath.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
                bath.setText("jLabel2");

                area.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
                area.setText("jLabel2");

                price.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
                price.setForeground(new java.awt.Color(30, 11, 146));
                price.setText("jLabel2");

                panelHolderLocation.setBackground(new java.awt.Color(253, 245, 230));
                panelHolderLocation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                street.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
                street.setText("jLabel2");
                panelHolderLocation.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 33));

                city.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
                city.setText("jLabel2");
                panelHolderLocation.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 81, 33));

                barangay.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
                barangay.setText("jLabel2");
                panelHolderLocation.add(barangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 81, 33));

                province.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
                province.setText("jLabel2");
                panelHolderLocation.add(province, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 81, 33));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(newPropertyPanel);
                newPropertyPanel.setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(bed)
                                .addGap(58, 58, 58)
                                .addComponent(bath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(panelHolderLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHolderLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                
                for(int i = 0; i < propertyDetails.length;i++) {
                    
                    if(i==3) {
                        title.setText(propertyDetails[i]);
                    }else if(i==6) {
                        price.setText(propertyDetails[i]);
                    }else if(i==7) {
                        bed.setText(propertyDetails[i]);
                    }else if(i==8) {
                        bath.setText(propertyDetails[i]);
                    }else if(i==9) {
                        area.setText(propertyDetails[i]);
                    }else if(i==14) {
                        province.setText(propertyDetails[i]);
                    }else if(i==15) {
                        city.setText(propertyDetails[i]);
                    }else if(i==16) {
                        barangay.setText(propertyDetails[i]);
                    }else if(i==17) {
                        street.setText(propertyDetails[i]);
                    }
                    
                }
                
                newPropertyPanel.add(title);
                newPropertyPanel.add(price);
                newPropertyPanel.add(bath);
                newPropertyPanel.add(area);
                newPropertyPanel.add(bed);
                newPropertyPanel.add(street);
                newPropertyPanel.add(barangay);
                newPropertyPanel.add(province);
                newPropertyPanel.add(city);
                newPropertyPanel.add(panelHolderLocation);
                newPropertyPanel.add(photo);
                
                propertiesPanel.add(newPropertyPanel);
                
                propertiesPanel.revalidate();
                propertiesPanel.repaint();
                
                
            }
            
            

        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        
    }
    
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        title = genInformationTab2.getTitle();
        description = genInformationTab2.getDescription();
        status = keyInformationTab2.getStatus();
        price = keyInformationTab2.getPrice();
        bedrooms = keyInformationTab2.getBedrooms();
        baths = keyInformationTab2.getBaths();
        area = keyInformationTab2.getArea();
        block = keyInformationTab2.getBlock();
        subdivisionName = keyInformationTab2.getSubdivisionName();
        photo = photosAndMediaTab2.imageFilePath;
        media = photosAndMediaTab2.otherImageFilePath;
        province = locationTab1.getProvince();
        city = locationTab1.getCity();
        barangay = locationTab1.getBarangay();
        street = locationTab1.getStreet();
        
        
        try {
            createNewProperty();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void listPropertyPanelHoderMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_listPropertyPanelHoderMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_listPropertyPanelHoderMouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
//        propertiesPanel.removeAll();
//        propertiesPanel.validate();
        
        

//        File propertyFile = new File("properties.txt");
//       
//        
//        try {
//            
//
//            if(propertyFile.createNewFile()) {
//                System.out.println("File is Created");
//            }else {
//                System.out.println("File Already Existed");
//            }
//
//            BufferedReader reader = new BufferedReader(new FileReader(propertyFile));
//
//            String line;
//            while((line = reader.readLine())!=null) {
//                String[] propertyDetails = line.split(",");
//
//                displayPropertiesDashboard displayAll = new displayPropertiesDashboard(
//                    propertyDetails[3],propertyDetails[6],propertyDetails[7],propertyDetails[8],propertyDetails[9]
//                    ,propertyDetails[14],propertyDetails[15],propertyDetails[16],propertyDetails[17]);
//                
//                        
//                propertiesPanel.add(displayAll);
//                
//                
//                displayAll.setVisible(true);
//                displayAll.revalidate();
//                displayAll.repaint();
//                
//                
//              
//            }
//            reader.close();
//            
//            
//            
//            
//        }catch (IOException ex) {
//            ex.printStackTrace();
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    public String createRandomFileName() {
        
        int number = (int) ((Math.random() * (1001 - 1)) + 1);
        
        String fileName = "property"+number;
        
        return fileName;  
    }
    
    
    public void createNewProperty() throws IOException {
        
        File propertiesFile = new File("properties.txt");
        
        try {
            if (propertiesFile.createNewFile()) {
                System.out.println("File is Created");
            }else {
                System.out.println("File Already Existed");
            }
        } catch(IOException e) {
            e.printStackTrace();
        }
        
        FileWriter fileWriter = new FileWriter(propertiesFile,true);
        
        fileWriter.write(createRandomFileName());
        fileWriter.write(",");
        
        if(genInformationTab2.isSellOpaque){
            fileWriter.write("Sell");
        }
        if(genInformationTab2.isRentOpaque){
            fileWriter.write("Rent");
       }
        
        fileWriter.write(",");fileWriter.write(genInformationTab2.propertyType);
        
        fileWriter.write(",");fileWriter.write(title);
        
        fileWriter.write(",");fileWriter.write(description);
        
        fileWriter.write(",");fileWriter.write(status);
        
        fileWriter.write(",");fileWriter.write(price);
        
        fileWriter.write(",");fileWriter.write(bedrooms);
        
        fileWriter.write(",");fileWriter.write(baths);
        
        fileWriter.write(",");fileWriter.write(area);
        
        fileWriter.write(",");fileWriter.write(block);
        
        fileWriter.write(",");fileWriter.write(subdivisionName);
        
        fileWriter.write(",");fileWriter.write(photo);
        
        fileWriter.write(",");fileWriter.write(media);
        
        fileWriter.write(",");fileWriter.write(province);
        
        fileWriter.write(",");fileWriter.write(city);
        
        fileWriter.write(",");fileWriter.write(barangay);
        
        fileWriter.write(",");fileWriter.write(street);
        
        fileWriter.write("\n");
        
        fileWriter.close();
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardPanel;
    private realestate.GenInformationTab genInformationTab2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private realestate.KeyInformationTab keyInformationTab2;
    private javax.swing.JLabel listPropertyNameLabel;
    private javax.swing.JPanel listPropertyPanel;
    private javax.swing.JPanel listPropertyPanelHoder;
    private realestate.LocationTab locationTab1;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JPanel managementPropertyTab;
    private realestate.PhotosAndMediaTab photosAndMediaTab2;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
