/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package realestate;

import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author jcost
 */
public class displayPropertiesDashboard extends javax.swing.JPanel {

    /**
     * Creates new form displayPropertiesDashboard
     */
    
    
    public displayPropertiesDashboard(String titleDetail, String priceDetail, String bedDetail, String bathDetail, String areaDetail, String provinceDetail, String cityDetail, String barangayDetail, String streetDetail, String photoDetail) {
        initComponents();
        title.setText(titleDetail);
        price.setText(priceDetail);
        bed.setText(bedDetail);
        bath.setText(bathDetail);
        area.setText(areaDetail);
        
        
        ImageIcon imageIcon = new ImageIcon(photoDetail);
        Image img = imageIcon.getImage();
        Image imageScaled = img.getScaledInstance(260, 110, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        photo.setIcon(scaledIcon);
        
        province.setText(provinceDetail);
        city.setText(cityDetail);
        barangay.setText(barangayDetail);
        street.setText(streetDetail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        bed = new javax.swing.JLabel();
        bath = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        street = new javax.swing.JLabel();
        barangay = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 245, 230));
        setPreferredSize(new java.awt.Dimension(270, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        title.setText("jLabel2");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 266, 24));

        bed.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bed.setText("jLabel2");
        add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 24));

        bath.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bath.setText("jLabel2");
        add(bath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 24));

        area.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        area.setText("jLabel2");
        add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 24));

        price.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        price.setForeground(new java.awt.Color(30, 11, 146));
        price.setText("jLabel2");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 249, 53));

        jPanel1.setBackground(new java.awt.Color(253, 245, 230));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        street.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        street.setText("jLabel2");
        jPanel1.add(street);

        barangay.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        barangay.setText("jLabel2");
        jPanel1.add(barangay);

        city.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        city.setText("jLabel2");
        jPanel1.add(city);

        province.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        province.setText("jLabel2");
        jPanel1.add(province);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 110));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JLabel barangay;
    private javax.swing.JLabel bath;
    private javax.swing.JLabel bed;
    private javax.swing.JLabel city;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel price;
    private javax.swing.JLabel province;
    private javax.swing.JLabel street;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
