/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package realestate;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author jcost
 */
public class ManagePropertiesObjects extends javax.swing.JPanel {

    /**
     * Creates new form displayPropertiesDashboard
     */
    
    public dashboard frame;
    public String bedIcon = "bedIcon.png";
    public String bathIcon = "bathIcon.png";
    public String areaIcon = "areaIcon.png";
    
    public void icon(String path, JLabel component){
        ImageIcon imageIcon =  new ImageIcon(path);
        Image img = imageIcon.getImage();
        Image imageScaled = img.getScaledInstance(20, 15, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        component.setIcon(scaledIcon);
    }
    
    
    public ManagePropertiesObjects(String propertyName, String titleDetail, String priceDetail, String bedDetail, String bathDetail, String areaDetail, String provinceDetail, String cityDetail, String barangayDetail, String streetDetail, String photoDetail, dashboard frame) {
        initComponents();
        this.frame = frame;
        title.setText(titleDetail);
        price.setText(priceDetail);
        bed.setText(bedDetail);
        bath.setText(bathDetail);
        area.setText(areaDetail);
        
        
        editButton.setName(propertyName);
        editButton.setFocusable(false);
        
        deleteButton.setName(propertyName);
        deleteButton.setFocusable(false);
        
        ImageIcon imageIcon = new ImageIcon(photoDetail);
        Image img = imageIcon.getImage();
        Image imageScaled = img.getScaledInstance(250, 170, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        photo.setIcon(scaledIcon);
        
        icon(bedIcon,jLabel1);
        icon(bathIcon,jLabel2);
        icon(areaIcon,jLabel3);
        
        province.setText(provinceDetail);
        city.setText(cityDetail);
        barangay.setText(barangayDetail);
        street.setText(streetDetail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        street = new javax.swing.JLabel();
        barangay = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bed = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bath = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 245, 230));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 170, 170), 3));
        setPreferredSize(new java.awt.Dimension(270, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        title.setText("jLabel2");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 266, 24));

        jPanel1.setBackground(new java.awt.Color(253, 245, 230));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        street.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        street.setText("jLabel2");
        jPanel1.add(street);

        barangay.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        barangay.setText("jLabel2");
        jPanel1.add(barangay);

        city.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        city.setText("jLabel2");
        jPanel1.add(city);

        province.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        province.setText("jLabel2");
        jPanel1.add(province);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 170));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 170));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        bed.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bed.setText("jLabel2");
        jPanel3.add(bed);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8);

        bath.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bath.setText("jLabel2");
        jPanel7.add(bath);

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 70, 30));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10);

        area.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        area.setText("jLabel2");
        jPanel9.add(area);

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 70, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 11, 146));
        jLabel4.setText("Php");
        jPanel4.add(jLabel4);

        price.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 28)); // NOI18N
        price.setForeground(new java.awt.Color(30, 11, 146));
        price.setText("jLabel2");
        jPanel4.add(price);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 50));

        editButton.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 170, 170), 3, true));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 60, 30));

        deleteButton.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 170, 170), 3, true));
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JLabel barangay;
    private javax.swing.JLabel bath;
    private javax.swing.JLabel bed;
    private javax.swing.JLabel city;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel price;
    private javax.swing.JLabel province;
    private javax.swing.JLabel street;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
